### ISSUE TITLE
Output to Project Muse

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#102]

**Comment by vincentwj** [comment]
Feedback from Project Muse upon ingesting Thoth ONIX:

>The book was Love Don't Need A Reason.  The specific problem was the ampersand in the subtitle, which was originally provided as <Subtitle>The Life & Music of Michael Callen</Subtitle>.  When I changed it to <Subtitle>The Life &amp; Music of Michael Callen</Subtitle> it ingested successfully.

>That is the only feedback I have to provide because otherwise everything was great.

**Comment by ja573** [comment]
Could you elaborate a bit more on the subtitle issue? I can't see a difference in the ampersand..

**Comment by vincentwj** [comment]
Done!

**Comment by vincentwj** [comment]
their ingest couldn't deal with `&` in the title

**Comment by ja573** [comment]
Ahh right. We'll need to fix this with #145

**Comment by rhigman** [comment]
Hi @vincentwj, I'm looking at #145 and it appears that `&` should already be being written out as `&amp;`. Can you tell me more about how you passed the ONIX files to Project Muse so I can work out where this is falling down?

The output of the "Metadata > ONIX" button for "Love Don't Need A Reason" is shown here:
https://api.staging.thoth.openbookpublishers.com/onix/636a5aa6-1d37-4cd2-8742-4dcad8c67e0c

But the source code for the page shows that the `&` is indeed underlyingly a `&amp;`:
view-source:https://api.staging.thoth.openbookpublishers.com/onix/636a5aa6-1d37-4cd2-8742-4dcad8c67e0c

**Comment by vincentwj** [comment]
I copypasted the text between <Product> and </Product> into a new ONIX file which contained several other books. They then ingested that file. So perhaps it went wrong during the copypasting?

**Comment by vincentwj** [comment]
Shouldn't this issue be closed?
