### ISSUE TITLE
Ensure empty data is sent as null not as empty strings

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#118]
We often have eISBNs before full-text URL for PDF publications. It would be useful to be able to add these without incurring an error message.

Sample error message:

```
Could not deserialize a successful request. With error: , and content: {"data":null,"errors":[{"message":"new row for relation \"publication\" violates check constraint \"publication_isbn_check\"","locations":[{"line":8,"column":9}],"path":["createPublication"]}]}
```

**Comment by vincentwj** [comment]
I think what caused the error and that is that I didn't put hyphens in the ISBN number. That seems to be obligatory.

**Comment by ja573** [comment]
Yes, hyphens are mandatory in the database. At some point conversion could be done automatically with #125

**Comment by ja573** [comment]
This is merged and live. We'll reopen if the issue persists
