### ISSUE TITLE
Add created and updated dates to each table

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#121]
It would be useful to see the latest additions in the [Works](https://staging.thoth.openbookpublishers.com/admin/works) overview. In order to do so, I propose a column "Date Created" as well as the possibility to [sort](https://github.com/thoth-pub/thoth/issues/120)

**Comment by ja573** [comment]
Database attributes are in place. Now we need to 1) update the schema file in the API to include the attributes 2) add the attributes to the structures in the models 3) add the attributes to the graphql schema
