### ISSUE TITLE
Rename Work Type "Edited Book" to "Edited Collection"

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#123]
"Edited Book" is potentially confusing, as Monographs can also have an editor. "Edited Collection" suggests more clearly that this is a collection of chapters authored by different authors.

**Comment by ja573** [comment]
I'm not entirely sure about this one. I had chosen edited book as the terminology used by Crossref. I'd say collection might be misleading as a work type, since it may suggest a collection of books rather than chapters

**Comment by vincentwj** [comment]
Fine enough, if it's crossref speak, who am I to argue! Withdrawn!
