### ISSUE TITLE
Punctum internal references should be strings, not integers

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#124]
upon ingest punctum internal references have been transformed into integers, whereas it is should be a four-number string

0006 not 6
0239 not 239
etc.
<img width="334" alt="Screenshot 2020-11-17 at 22 05 42" src="https://user-images.githubusercontent.com/20144127/99450565-38e31d80-2921-11eb-8cca-b70d0c7af3e5.png">

**Comment by ja573** [comment]
Sorry, I hadn't noticed that. I seem to have overwritten these when cleaning some data in the CSV you sent me; libreoffice converted them to integers before I imported them. i.e. this is not a bug in Thoth

I'm going to change the references programmatically in the database

**Comment by vincentwj** [comment]
got it, thanks!

**Comment by ja573** [comment]
Done
