### ISSUE TITLE
Do not exit Work when saving it

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#127]
Now you automatically leave a work when you Save it. Suggest to stay within the work, because usually you do multiple updates or want to keep the window open for later reference. Alternatively, have separate "Save" and "Save and Exit" buttons.

**Comment by ja573** [comment]
I think this could be a good first issue for you, @rhigman . I'm assigning it to you now so I don't forget, but obviously let's wait until you are fully set up
