### ISSUE TITLE
Output to Wikidata

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#138]
https://github.com/thoth-pub/thoth/wiki/Wikidata

**Comment by vincentwj** [comment]
Simon's work: https://github.com/SimonXIX/thoth_wikidata_integration

**Comment by SimonXIX** [comment]
The biggest chunk of my investigatory work that I hope will be useful is the authentication code for Wikidata (and test.wikidata.org) in wikidata.py and the 'translation' between Thoth's metadata structure and Wikidata's metadata structure. I tried to follow Wikidata's guidance around bibliographic item properties outlined here: https://www.wikidata.org/wiki/Wikidata:WikiProject_Books

**Comment by rhigman** [comment]
To investigate: can we use Simon's program to provide interim output (for WP6 project) as a stop-gap before Thoth-native Wikidata output is available?

@vincentwj, this is assigned to you "to investigate" - can you remind me which elements still need to be clarified before we can work on this/what progress you've made so far?

**Comment by rhigman** [comment]
Re the above, Rupert has put Simon Bowie and Simon Worthington in touch to discuss WP6's requirements. Thoth-native output cannot be created until we have implemented the planned submission service (push mechanism) to submit data directly to the Wikidata API.

Note that [the Wikidata guidelines on submitting data](https://www.wikidata.org/wiki/Wikidata:Data_donation#How_to_add_data_to_Wikidata) require discussion with the Wikidata community before proceeding.

**Comment by SimonXIX** [comment]
Simon W. notes that in his discussions with Wikidata and MediaWiki, disambiguation has been raised as the major issue for publishers submitting to Wikidata, as in determining systematically if a publication is already in Wikidata so they don't end up with loads of duplicate records. When we get in touch with Wikidata about their preferred approach, we should be sure to discuss this.
