### ISSUE TITLE
Create warning when creating a duplicate Contributor/Work

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#150]
I created a new contributor that already existed and now I don't know which one was the original, so perhaps create a warning when attempting to create a duplicate.
<img width="1093" alt="Screenshot 2021-01-03 at 09 31 01" src="https://user-images.githubusercontent.com/20144127/103474689-b4e8d600-4da6-11eb-9e1d-a94b45acd16e.png">

**Comment by rhigman** [comment]
Hi @vincentwj, while we work on adding this, if you still have the issue with not being able to tell these duplicate entries apart, you should now be able to work out which is which by clicking through to each of them. #171 added a banner to contributor pages showing which works they're associated with, so presumably (hopefully!) the original will have some entries and the duplicate won't :)

**Comment by vincentwj** [comment]
I saw the banner, which is super helpful! Thanks!!
