### ISSUE TITLE
Error when adding Publication

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#197]
For the Book of Anonymity, I cannot add new publications without ISBN. This didn't happen before.

I get the following error:

`Could not deserialize a successful request. With error: , and content: {"data":{"createPublication":{"publicationId":"7228bf51-75e9-462b-8ccb-c93990006380","publicationType":"PAPERBACK","isbn":null,"publicationUrl":"https://www.amazon.com/dp/1953035302","workId":"940d0880-83b5-499d-9f39-1bf30ccfc4d0"}}}`

**Comment by ja573** [comment]
Just FYI, data is being saved properly, but the GUI is not displaying it properly (e.g. if you refresh you should see what you've entered). We'll have a fix in place asap

**Comment by vincentwj** [comment]
Got it, thanks!
