### ISSUE TITLE
Allow filtering graphql queries with enum types

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#202]
Emulate the `publication_type` filtering in `work.publications()` for other objects that have a type/custom_enum:

- [x] work (`work_type`, `work_status`)
- [x] publication (`publication_type`)
- [x] subject (`subject_type`)
- [x] price (`currency_code`)
- [x] language (`language_code`, `language_relation`)
- [x] series (`series_type`)
- [x] contribution (`contribution_type`)

**Comment by rhigman** [comment]
Also add filtering by `doi` (string, not enum) to `work()` - possibly as a separate query
