### ISSUE TITLE
Please add link to documentation

### ISSUE THREAD

**Issue by eshellman** [thoth-pub/thoth#213]
Rupert asked me to take a look at Thoth, but I have been unable to find any documentation.

**Comment by ja573** [comment]
If you are interested in the API, the easiest is to inspect the schema with graphiql at https://api.thoth.pub/graphiql (click on "Docs" at the top right)

**Comment by eshellman** [comment]
No, I mean Thoth. Adding a link to https://api.thoth.pub/graphiql would be a good addition; that schema's documentation is telegraphic.
What user stories are addressed by the api? Maybe a few example queries for the live dataset would help?
Is there a roadmap?
What set of problems is Thoth designed to solve?
Are there design documents anywhere? User requirements?

**Comment by ja573** [comment]
So far everything is work in progress and that type of documents are scattered. The project wiki could be a good place to start (though it needs tidying up) - it provides information of the data formats and platforms Thoth will output and how it links to the [scoping report](https://doi.org/10.21428/785a6451.939caeab)

**Comment by eshellman** [comment]
That's what I was looking for! I will submit a PR.

**Comment by ja573** [comment]
Great, thank you! If you do, please use `develop` as the base branch (instead of `master`) - we use [git flow](https://datasift.github.io/gitflow/) as our branching model. (We don't yet have a PR template.)
