### ISSUE TITLE
Search on Title in Publications

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#231]
I would be helpful if in Publications you could search not only under ISBN and URL but also Title.

**Comment by ja573** [comment]
I think this is mainly an issue with the way the interfaces are structured at present. To allow this we'll need to change the API filtering to link multiple objects and I'm not entirely sure if we should do that at this stage.

A simply change we could do to solve the navigation issue could be to link to the publication page from the work > publications box, e.g. clicking  on a publication within a work page takes you to the publication page. Would this (partially) solve the issue, @vincentwj ?

**Comment by vincentwj** [comment]
perfect!
