### ISSUE TITLE
Units of measure and value conversions

### ISSUE THREAD

**Issue by timelf** [thoth-pub/thoth#259]
Given that some printers measure in centimeters and others in inches, would it be possible (1) for an user entering metadata to select the unit of measure they wish to use (inches, centimeters, millimeters), and (2) have users interacting with records in Thoth chose what unit of measure they would like to see, meaning the the length values would be automatically converted?

**Comment by ja573** [comment]
Related to #258 

Short answer: absolutely

We need to discuss whether to store the value in multiple measures, store it in millimetres and expose it in various measures, or simply use millimetres as the canonical measure but convert to it in the GUI

**Comment by ja573** [comment]
We'll do option 2: store the measure in millimetres but (1) expose it in inches, mm, and cm in graphql; (2) in the APP, allow user to select unit measure and convert automatically to mm in the backend

**Comment by slimdave** [comment]
If it helps, the route we took with this in Consonance is to expose measurements in GQL as productHeight, productWidth etc, returning values in mm/gr by default, with an ENUM unit argument to allow it to be converted.

```
  """
  The height of the entire product, including boards and packaging, in the form
  in which it is presented or packaged for retail sale
  """
  productHeight(
    """
    The units of measurement (default is mm)
    """
    unit: LengthUnit
  ): Float

  """
  The width of the entire product, including boards and packaging, in the form
  in which it is presented or packaged for retail sale
  """
  productWidth(
    """
    The units of measurement (default is mm)
    """
    unit: LengthUnit
  ): Float



enum LengthUnit {
  """
  Centimetres
  """
  CM

  """
  Inches
  """
  IN

  """
  Millimetres
  """
  MM
}
```

This lets users:
```
query {
  products(productSearch: {onix21ProductFormCodeIn: [BB]}){
    id
    ... on PhysicalBookProduct {
      productHeightMm: productHeight
      productHeightCm: productHeight(unit: CM)
      productHeightIn: productHeight(unit: IN)
    }
  }
}

...

{
  "data": {
    "products": [
      {
        "id": 19,
        "productHeightMm": 254.0,
        "productHeightCm": 25.4,
        "productHeightIn": 10.0
      },
      {
        "id": 21,
        "productHeightMm": 254.0,
        "productHeightCm": 25.4,
        "productHeightIn": 10.0
      },
      {
        "id": 22,
        "productHeightMm": 254.0,
        "productHeightCm": 25.4,
        "productHeightIn": 10.0
      },
```

**Comment by ja573** [comment]
Thanks, @slimdave - that is very useful indeed. What license does that snippet have :smiley:  ?

**Comment by slimdave** [comment]
Happy for you to use it! There's a lot of commonality between what we're doing, and I think the closer our implementations of book metadata GQL are the better. Maybe it's the start of "ONIX for GraphQL".

**Comment by rhigman** [comment]
@slimdave Thanks! One query: what conversion factor(s) are you using? An exact conversion would be 1in = 25.4mm, however, it looks like printing companies use inch/mm values as shorthand for standard sizes rather than precise measurements. For example, Lightning Source state their smallest standard trim size as "4in x 6in (152mm x 102mm)" (https://www.ingramcontent.com/Documents/LSI_FileCreationGuide.pdf, page 42). However, 4*25.4 = 101.6 (rather than 102), and 6*25.4 = 152.4 (rather than 152).

Converting in this way and then rounding to the nearest mm looks like it might work, but converting back from mm to inches gets more complicated, at least for the Lightning Source sizes. In some cases they seem to round to the nearest inch, in other cases to an arbitrary number of decimal places (e.g. "6.625in x 10.25in (260mm x 168mm)"). If you've been through this wrangling already and worked out a reliable solution, it would be great to know - especially as it would be good for measurements to display/convert consistently across our platforms!

**Comment by slimdave** [comment]
@rhigman yeah this is a tricky issue. We convert inches to mm by rounding to the integer, and we convert mm to inches by rounding up to the nearest sixteenth of an inch.

That's not perfect though, so it's under review. e.g. 7in -> 178mm -> 7.0625in. 

The current thought is either:
```
convert to inches, then round to the 1/8th of an inch, then convert back to mm and round to the integer to see if that produces the initial mm we started with, and if it does then use the 1/8th rounding, otherwise use the 1/16th rounding
```
or
```
use a lookup table
```
Ugh.

**Comment by rupertgatti** [comment]
Assuming that we are storing the measurement units in mm, but allowing publisher to enter sizes in either mm or inches depending on what the book has been set in - then the critical conversion is from inches to mm and back to inches.  If  book has been set in mm and returns a 'wierd' number (not 1/16th or 1/32) in inches then that is a signal that the book wasn't set in inches, and 'correcting it' to the nearest 1/16 in seems wrong to me. But if the book was set in inches - it is important we get return the inches measure right.  So I think we only need worry about the inches - mm - inches roundtrip, but not the mm - inches - mm route.  Given that 1/16 in > 1.5mm there should be no problem keeping mm as integers and backing out the correct inches measure to 1/16th if we keep 4 decimal places for inches.

**Comment by rhigman** [comment]
I've collated all of the inch/mm values listed in the Lightning Source table, as linked above, to give me a set of (I hope) popular dimensions to test our conversions on.

As Rupert suggested, when converting from inches to mm, I've rounded the result to the nearest mm, and when converting from mm to inches, I've first rounded the result to 4 decimal places, and then re-rounded to the nearest 1/16th of an inch.

I've then converted each of the listed inch values to mm and then back to inches again, and each of the listed mm values to inches and then back to mm again. The results are tabulated below.

In most cases, the mm > inch > mm round trip returns the same value as was initially supplied, but notably, there are four cases where it doesn't. For inches > mm > inches, there are many more cases where the returned value doesn't match the initial value, although this could be put down to Lightning Source's somewhat inconsistent choice of values.

It's important to note that we may end up doing the mm > inch > mm conversion more often than intuition would suggest. Say a user has units set to inches, and views a work whose values were originally set in mm. The user might then edit a (different) field on the work and re-save it. Currently, we re-save by sending all of the work's values back down to the database from the UI, not just the values that have been changed. We would therefore end up converting the displayed inch values back to mm and re-saving them, overwriting the original mm values. (There would be no practical way for us to distinguish between works 'originally' saved in mm and inches and treat them differently when displaying/saving.)

@rupertgatti, if you're still happy with the suggested degrees of rounding, I'll go ahead and implement them. @timelf, as you originally requested this feature, perhaps you'd like to weigh in at this point to confirm that it's doing what you'd want it to.

```
4in      > 102mm   > 4in       (equal)
4.25in   > 108mm   > 4.25in    (equal)
4.37in   > 111mm   > 4.375in   (mismatched)
4.72in   > 120mm   > 4.75in    (mismatched)
5in      > 127mm   > 5in       (equal)
5.06in   > 129mm   > 5.0625in  (mismatched)
5.25in   > 133mm   > 5.25in    (equal)
5.5in    > 140mm   > 5.5in     (equal)
5.83in   > 148mm   > 5.8125in  (mismatched)
6in      > 152mm   > 6in       (equal)
6.14in   > 156mm   > 6.125in   (mismatched)
6.5in    > 165mm   > 6.5in     (equal)
6.625in  > 168mm   > 6.625in   (equal)
6.69in   > 170mm   > 6.6875in  (mismatched)
7in      > 178mm   > 7in       (equal)
7.44in   > 189mm   > 7.4375in  (mismatched)
7.48in   > 190mm   > 7.5in     (mismatched)
7.5in    > 191mm   > 7.5in     (equal)
7.81in   > 198mm   > 7.8125in  (mismatched)
8in      > 203mm   > 8in       (equal)
8.25in   > 210mm   > 8.25in    (equal)
8.268in  > 210mm   > 8.25in    (mismatched)
8.27in   > 210mm   > 8.25in    (mismatched)
8.38in   > 213mm   > 8.375in   (mismatched)
8.5in    > 216mm   > 8.5in     (equal)
9in      > 229mm   > 9in       (equal)
9.21in   > 234mm   > 9.1875in  (mismatched)
9.25in   > 235mm   > 9.25in    (equal)
9.61in   > 244mm   > 9.625in   (mismatched)
9.69in   > 246mm   > 9.6875in  (mismatched)
10in     > 254mm   > 10in      (equal)
10.25in  > 260mm   > 10.25in   (equal)
10.75in  > 273mm   > 10.75in   (equal)
10.88in  > 276mm   > 10.875in  (mismatched)
11in     > 279mm   > 11in      (equal)
11.693in > 297mm   > 11.6875in (mismatched)

102mm  > 4in        > 102mm   (equal)
108mm  > 4.25in     > 108mm   (equal)
111mm  > 4.375in    > 111mm   (equal)
120mm  > 4.75in     > 121mm   (mismatched)
127mm  > 5in        > 127mm   (equal)
129mm  > 5.0625in   > 129mm   (equal)
133mm  > 5.25in     > 133mm   (equal)
140mm  > 5.5in      > 140mm   (equal)
148mm  > 5.8125in   > 148mm   (equal)
152mm  > 6in        > 152mm   (equal)
156mm  > 6.125in    > 156mm   (equal)
165mm  > 6.5in      > 165mm   (equal)
168mm  > 6.625in    > 168mm   (equal)
170mm  > 6.6875in   > 170mm   (equal)
178mm  > 7in        > 178mm   (equal)
189mm  > 7.4375in   > 189mm   (equal)
190mm  > 7.5in      > 191mm   (mismatched)
191mm  > 7.5in      > 191mm   (equal)
198mm  > 7.8125in   > 198mm   (equal)
203mm  > 8in        > 203mm   (equal)
210mm  > 8.25in     > 210mm   (equal)
213mm  > 8.375in    > 213mm   (equal)
216mm  > 8.5in      > 216mm   (equal)
229mm  > 9in        > 229mm   (equal)
234mm  > 9.1875in   > 233mm   (mismatched)
235mm  > 9.25in     > 235mm   (equal)
244mm  > 9.625in    > 244mm   (equal)
246mm  > 9.6875in   > 246mm   (equal)
254mm  > 10in       > 254mm   (equal)
260mm  > 10.25in    > 260mm   (equal)
273mm  > 10.75in    > 273mm   (equal)
276mm  > 10.875in   > 276mm   (equal)
280mm  > 11in       > 279mm   (mismatched)
297mm  > 11.6875in  > 297mm   (equal)
```

**Comment by rupertgatti** [comment]
Hmm - I suspect the problem is the rounding to 1/32 inch. The mismatches seem to occur when the initial inch value is not a unit of 1/16th of an inch.  Will inch measurements be inputted in decimal or in 32ths?  If the former - we may get better results ditching the 1/32th rounding and just going with 2 or 3 dec places.

**Comment by rhigman** [comment]
At the moment, the UI allows inches to be input in decimal up to 4 decimal places - it didn't seem reasonable to restrict input to 16ths (or 32ths) when so many of the standard Lightning Source dimensions are not represented in 16ths (or 32ths).

I've re-run the tests above without the 1/16th inch re-rounding, first rounding inches only to 2 decimal places, then rounding inches only to 3 decimal places. As you can see, we now get mismatches mainly where the initial inch value was a whole/half/quarter inch and the reconversion has more degrees of accuracy. It does, however, fix the mm round trip issues. Let me know if you think this is better.

```
With inches rounded to 2 decimal places and no further rounding to 16ths:

4in      > 102mm  > 4.02in   (mismatched)
4.25in   > 108mm  > 4.25in   (equal)
4.37in   > 111mm  > 4.37in   (equal)
4.72in   > 120mm  > 4.72in   (equal)
5in      > 127mm  > 5in      (equal)
5.06in   > 129mm  > 5.08in   (mismatched)
5.25in   > 133mm  > 5.24in   (mismatched)
5.5in    > 140mm  > 5.51in   (mismatched)
5.83in   > 148mm  > 5.83in   (equal)
6in      > 152mm  > 5.98in   (mismatched)
6.14in   > 156mm  > 6.14in   (equal)
6.5in    > 165mm  > 6.5in    (equal)
6.625in  > 168mm  > 6.61in   (mismatched)
6.69in   > 170mm  > 6.69in   (equal)
7in      > 178mm  > 7.01in   (mismatched)
7.44in   > 189mm  > 7.44in   (equal)
7.48in   > 190mm  > 7.48in   (equal)
7.5in    > 191mm  > 7.52in   (mismatched)
7.81in   > 198mm  > 7.8in    (mismatched)
8in      > 203mm  > 7.99in   (mismatched)
8.25in   > 210mm  > 8.27in   (mismatched)
8.268in  > 210mm  > 8.27in   (mismatched)
8.27in   > 210mm  > 8.27in   (equal)
8.38in   > 213mm  > 8.39in   (mismatched)
8.5in    > 216mm  > 8.5in    (equal)
9in      > 229mm  > 9.02in   (mismatched)
9.21in   > 234mm  > 9.21in   (equal)
9.25in   > 235mm  > 9.25in   (equal)
9.61in   > 244mm  > 9.61in   (equal)
9.69in   > 246mm  > 9.69in   (equal)
10in     > 254mm  > 10in     (equal)
10.25in  > 260mm  > 10.24in  (mismatched)
10.75in  > 273mm  > 10.75in  (equal)
10.88in  > 276mm  > 10.87in  (mismatched)
11in     > 279mm  > 10.98in  (mismatched)
11.693in > 297mm  > 11.69in  (mismatched)

102mm   > 4.02in    > 102mm   (equal)
108mm   > 4.25in    > 108mm   (equal)
111mm   > 4.37in    > 111mm   (equal)
120mm   > 4.72in    > 120mm   (equal)
127mm   > 5in       > 127mm   (equal)
129mm   > 5.08in    > 129mm   (equal)
133mm   > 5.24in    > 133mm   (equal)
140mm   > 5.51in    > 140mm   (equal)
148mm   > 5.83in    > 148mm   (equal)
152mm   > 5.98in    > 152mm   (equal)
156mm   > 6.14in    > 156mm   (equal)
165mm   > 6.5in     > 165mm   (equal)
168mm   > 6.61in    > 168mm   (equal)
170mm   > 6.69in    > 170mm   (equal)
178mm   > 7.01in    > 178mm   (equal)
189mm   > 7.44in    > 189mm   (equal)
190mm   > 7.48in    > 190mm   (equal)
191mm   > 7.52in    > 191mm   (equal)
198mm   > 7.8in     > 198mm   (equal)
203mm   > 7.99in    > 203mm   (equal)
210mm   > 8.27in    > 210mm   (equal)
210mm   > 8.27in    > 210mm   (equal)
210mm   > 8.27in    > 210mm   (equal)
213mm   > 8.39in    > 213mm   (equal)
216mm   > 8.5in     > 216mm   (equal)
229mm   > 9.02in    > 229mm   (equal)
234mm   > 9.21in    > 234mm   (equal)
235mm   > 9.25in    > 235mm   (equal)
244mm   > 9.61in    > 244mm   (equal)
246mm   > 9.69in    > 246mm   (equal)
254mm   > 10in      > 254mm   (equal)
260mm   > 10.24in   > 260mm   (equal)
273mm   > 10.75in   > 273mm   (equal)
276mm   > 10.87in   > 276mm   (equal)
280mm   > 11.02in   > 280mm   (equal)
297mm   > 11.69in   > 297mm   (equal)
```

```
With inches rounded to 3 decimal places and no further rounding to 16ths:

4in       > 102mm   > 4.016in   (mismatched)
4.25in    > 108mm   > 4.252in   (mismatched)
4.37in    > 111mm   > 4.37in    (equal)
4.72in    > 120mm   > 4.724in   (mismatched)
5in       > 127mm   > 5in       (equal)
5.06in    > 129mm   > 5.079in   (mismatched)
5.25in    > 133mm   > 5.236in   (mismatched)
5.5in     > 140mm   > 5.512in   (mismatched)
5.83in    > 148mm   > 5.827in   (mismatched)
6in       > 152mm   > 5.984in   (mismatched)
6.14in    > 156mm   > 6.142in   (mismatched)
6.5in     > 165mm   > 6.496in   (mismatched)
6.625in   > 168mm   > 6.614in   (mismatched)
6.69in    > 170mm   > 6.693in   (mismatched)
7in       > 178mm   > 7.008in   (mismatched)
7.44in    > 189mm   > 7.441in   (mismatched)
7.48in    > 190mm   > 7.48in    (equal)
7.5in     > 191mm   > 7.52in    (mismatched)
7.81in    > 198mm   > 7.795in   (mismatched)
8in       > 203mm   > 7.992in   (mismatched)
8.25in    > 210mm   > 8.268in   (mismatched)
8.268in   > 210mm   > 8.268in   (equal)
8.27in    > 210mm   > 8.268in   (mismatched)
8.38in    > 213mm   > 8.386in   (mismatched)
8.5in     > 216mm   > 8.504in   (mismatched)
9in       > 229mm   > 9.016in   (mismatched)
9.21in    > 234mm   > 9.213in   (mismatched)
9.25in    > 235mm   > 9.252in   (mismatched)
9.61in    > 244mm   > 9.606in   (mismatched)
9.69in    > 246mm   > 9.685in   (mismatched)
10in      > 254mm   > 10in      (equal)
10.25in   > 260mm   > 10.236in  (mismatched)
10.75in   > 273mm   > 10.748in  (mismatched)
10.88in   > 276mm   > 10.866in  (mismatched)
11in      > 279mm   > 10.984in  (mismatched)
11.693in  > 297mm   > 11.693in  (equal)

102mm   > 4.016in   > 102mm  (equal)
108mm   > 4.252in   > 108mm  (equal)
111mm   > 4.37in    > 111mm  (equal)
120mm   > 4.724in   > 120mm  (equal)
127mm   > 5in       > 127mm  (equal)
129mm   > 5.079in   > 129mm  (equal)
133mm   > 5.236in   > 133mm  (equal)
140mm   > 5.512in   > 140mm  (equal)
148mm   > 5.827in   > 148mm  (equal)
152mm   > 5.984in   > 152mm  (equal)
156mm   > 6.142in   > 156mm  (equal)
165mm   > 6.496in   > 165mm  (equal)
168mm   > 6.614in   > 168mm  (equal)
170mm   > 6.693in   > 170mm  (equal)
178mm   > 7.008in   > 178mm  (equal)
189mm   > 7.441in   > 189mm  (equal)
190mm   > 7.48in    > 190mm  (equal)
191mm   > 7.52in    > 191mm  (equal)
198mm   > 7.795in   > 198mm  (equal)
203mm   > 7.992in   > 203mm  (equal)
210mm   > 8.268in   > 210mm  (equal)
210mm   > 8.268in   > 210mm  (equal)
210mm   > 8.268in   > 210mm  (equal)
213mm   > 8.386in   > 213mm  (equal)
216mm   > 8.504in   > 216mm  (equal)
229mm   > 9.016in   > 229mm  (equal)
234mm   > 9.213in   > 234mm  (equal)
235mm   > 9.252in   > 235mm  (equal)
244mm   > 9.606in   > 244mm  (equal)
246mm   > 9.685in   > 246mm  (equal)
254mm   > 10in      > 254mm  (equal)
260mm   > 10.236in  > 260mm  (equal)
273mm   > 10.748in  > 273mm  (equal)
276mm   > 10.866in  > 276mm  (equal)
280mm   > 11.024in  > 280mm  (equal)
297mm   > 11.693in  > 297mm  (equal)
```
