### ISSUE TITLE
Price field needs two digits after the decimal

### ISSUE THREAD

**Issue by timelf** [thoth-pub/thoth#260]
Currency data format should include two digits after the decimal.

**Comment by ja573** [comment]
@timelf can you specify where? The data is stored as [double precission](https://www.postgresql.org/docs/9.0/datatype-numeric.html) and should always be displayed with two decimals (unless the price is "0")

**Comment by rhigman** [comment]
Looks like the two decimals are only displayed if they're non-zero values - compare e.g. https://thoth.pub/admin/publication/a52d6230-d226-4053-b200-ef95f90c7fb1 and https://thoth.pub/admin/publication/7c902b8d-6185-44dd-b0ac-04d93120b31c.

**Comment by ja573** [comment]
Ok, i'm closing this for the time being. Feel free to reopen if needed
