### ISSUE TITLE
Funder DOI look up

### ISSUE THREAD

**Issue by timelf** [thoth-pub/thoth#265]
There appears to be nowhere to do a simple in-browser search of funders to find out if they are included in CrossRef's Funder Registry. Crossref provides tables with funder names and DOIs in either CSV or JSON, or a larger RDF files with additional relations, which it regularly updates: Is there some way we can create a means for users to search by funder name to find their DOIs?

**Comment by timelf** [comment]
Here is the Crossref page with info on retrieving updated funder registry files: https://www.crossref.org/documentation/funder-registry/accessing-the-funder-registry/

**Comment by ja573** [comment]
The easiest would probably be to integrate their [API](https://www.crossref.org/documentation/funder-registry/funder-data-via-the-api/)

**Comment by vincentwj** [comment]
As we are including ROR identifiers this becomes a moot point I think, since ROR includes Crossref funder IDs when present (ROR is comanaged by Crossref, and I understood from the webinar yesterday that though Funder DOIs will be maintained they will be slowly phased out in favor of ROR).
