### ISSUE TITLE
Use more fields when filtering in `contributors` query 

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#272]
At present search is done in `fullName` and `orcid`. We should include `lastName`, too. A use case is searching a contributor without their middle name doesn't return the expected contributor, e.g. filtering with "Martin Eve" doesn't return "Martin Paul Eve"s record.

**Comment by rhigman** [comment]
I attempted splitting the filter string on spaces in https://github.com/thoth-pub/thoth/pull/278/commits/d28fef68872b6734c1bcdece7344280164656005, but the results returned were poor, as the number of hits potentially increased every time a new word/name was added to the filter string - making it harder to see actual matches.
