### ISSUE TITLE
Add height/width measurement unit to cvs export

### ISSUE THREAD

**Issue by timelf** [thoth-pub/thoth#274]
How can we include the measurement unit for the height / width field in the cvs export: In the template I'm working on, I've added it as another field immediately after the heigh and width fields.
<img width="226" alt="Screen Shot 2021-08-13 at 12 43 18 PM" src="https://user-images.githubusercontent.com/4992179/129398860-f320b55a-0e05-4208-9e2a-96c6b0874be6.png">

**Comment by rhigman** [comment]
Added under https://github.com/thoth-pub/thoth/pull/279: CSV export now has separate fields for width (mm), width (cm), width (in), height (mm), height (cm) and height (in). Note that CSV exports can be publicly requested by anyone, and units selection is only available to logged-in users, so adding a separate "units" column (as in the screenshot) would not have been appropriate.
