### ISSUE TITLE
width/height not displayed correctly

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#300]
There are all kinds of weird "rounding" errors when putting in dimensions in inches. It would be great if the values I put in are actually displayed
<img width="623" alt="Screenshot 2021-10-19 at 15 42 06" src="https://user-images.githubusercontent.com/20144127/137922249-84039b88-d32e-4a3f-882d-1bf02e9288ef.png">

This should have been 7.5 x 6 for example.

**Comment by vincentwj** [comment]
Ah I see. Unfortunately this is really not acceptable, as US publishers need proper displaying of measurements. Rounding won't work, since there also book sizes like 6.21x9.14 in etc.

**Comment by vincentwj** [comment]
For example, if we at some point wanted to facilitate checking whether specific dimensions fit the KDP standards for wholesale distributions, these numbers need to be precise. I guess there are multiple other circumstances in which that holds.

**Comment by rhigman** [comment]
Proposed fix: store mm and inches separately in database; make both visible and editable at all times in user interface; convert one value automatically whenever the other value is edited, unless user selects option to override automatic conversion.

While fixing this, we will also take the opportunity to a) move the width/height from the work to the publication (paperbacks/hardbacks only), and b) add thickness (i.e. depth of spine).

**Comment by vincentwj** [comment]
I like this.
