### ISSUE TITLE
meta data for scholars

### ISSUE THREAD

**Issue by studiojulienmchardy** [thoth-pub/thoth#313]
Dear Thoth Superstars,

When you are on a book page on the Thoth homepage you can select to download metadata in different formats. Onix this that and the other. That's great but the formats that are offered refer to conventions that won't mean that much to most scholars. 

For scholars it would be great to add metadata format that is conform with their citation manager. Zotero, Endnote etc. It would be great to add that. 

#enhancement

**Comment by ja573** [comment]
This should be covered with #104 and #77

**Comment by studiojulienmchardy** [comment]
true, thanks Javi
