### ISSUE TITLE
Integrate Traditional Knowledge labels

### ISSUE THREAD

**Issue by rupertgatti** [thoth-pub/thoth#328]
Traditional Knowledge have a series of rights/reuse labels that can relate to knowledge base/material in a publication
These can be customised to describe specific types of conditions over reuse of the work - and might sit alongside alternative licences such as CC 
Each TK label is specific to a work/object and has a specific digital identifier which links to a curated hub/registry
The hub has an api
https://github.com/biocodellc/localcontexts_db/wiki/API-Documentation
https://localcontexts.org/tk-label-hub/
hopefully these will provide the necessary specification, but it seems that a single work can have multiple TK flags (each with it's own url) and each may have very individual requirements, so it may be necessary to store the specific text for each flag

TK are working with various agencies to include the flags in existing metadata schemas (eg MARC, DublinCore, etc). Some details on suggestions about how this can be incorporated has been developed - with examples at the base of this page:
https://loc.gov/item/2015655578

**Comment by vincentwj** [comment]
More info links:

- http://publications.ravenspacepublishing.org/as-i-remember-it/index
- http://digitalsqewlets.ca/index-eng.php
- https://passamaquoddypeople.com/digital-heritage/left-tide-take-back
- https://eos.org/articles/academic-citations-evolve-to-include-indigenous-oral-teachings
- https://loc.gov/item/2015655578
- https://github.com/biocodellc/localcontexts_db/wiki/API-Documentation
- https://localcontexts.org/tk-label-hub/
