### ISSUE TITLE
Contact Crossref books WG about the ISBN limit in DOI deposits

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#382]
In relation to #379

**Comment by rupertgatti** [comment]
Received from Patricia Feeney at CrossRef <[pfeeney@crossref.org](mailto:pfeeney@crossref.org)>

"I’m happy to raise the ISBN limit in a future schema update, I’m surprised we haven’t run into this before. We need to work out on our end what the downstream effects will be - we have a lot of old code that is used to process ISBNs, and I’m not sure if the 6 limit exists for a reason (maybe a limit in the database table?). If there is no issue on the metadata processing side, the change will be simple, but if it does require development changes we may not be able to make this change quickly.
I’ve created a JIRA ticket for this:
https://crossref.atlassian.net/browse/CR-521
and will keep you posted on our progress.
Best,
Patricia"
