### ISSUE TITLE
Generate MARC records

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#42]
With an open license for metadata reuse

**Comment by vincentwj** [comment]
Recommendation 33. COPIM needs to be able to produce MARC records for OA monographs that have an open licence to promote re-use.

**Comment by vincentwj** [comment]
Recommendation 45. COPIM must include the new versions of MARC 21 506, 540 and 856 fields

**Comment by vincentwj** [comment]
See here MARC details for records send to ExLibris. Maybe keep this in mind too? https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Electronic_Resource_Management/030_Working_with_Local_Electronic_Resources/070Contributing_to_the_Community_Zone_%E2%80%93_Bibliographic_Records

**Comment by vincentwj** [comment]
Wowza fantastic!
