### ISSUE TITLE
Output to JSTOR

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#44]

**Comment by rupertgatti** [comment]
Recommendation 13. Some OA publishers see JSTOR as an essential part of their dissemination. Therefore, COPIM needs to engage with JSTOR

**Comment by vincentwj** [comment]
Feedback by JSTOR on our ONIX files:

Thank you for reaching out.  Overall this ONIX is valid, but I want to touch base about some fields that are preventing us from processing these files:

1. Unpriced Item Type 01 indicates that the book is free of charge, but we are receiving these titles with Unpriced Item Type 04, which means "Contact supplier."  Would it be possible to have books delivered with 01 instead?


2. Publishing Date Role 01 signifies the publication date, but we are receiving these titles with only Publication Date Role 19, which means "Publication date of print counterpart." Would it be possible to include Publishing Date Role 01, with the year, month, and day all included?


3. EDItEUR's best practices for OA include the use of an OA flag, which would appear in the file looking something like this:

    <TextContent>
      <TextType>20</TextType>
      <ContentAudience>00</ContentAudience>
      <Text>Open Access</Text>
    </TextContent>

This is absent from this metadata.  Would Thoth be able to accommodate this JSTOR requirement?
