### ISSUE TITLE
Connect to BL

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#45]
Recommendation 36. As the main supplier of data to the British Library CIP programme and to UK academic libraries, COPIM should liaise with BDS in order to understand workflows and business models

**Comment by vincentwj** [comment]
Recommendation 37. COPIM needs to liaise with the British Library regarding metadata supply and free distribution of OA monograph metadata on a CC0 licence.

**Comment by rupertgatti** [comment]
I have arranged a meeting with Andrew.MacEwan@bl.uk  who is involved with the British National Bibliography https://bnb.data.bl.uk/  for Aug 5th at 11am (UK time).
