### ISSUE TITLE
Output to OAPEN

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#48]

**Comment by vincentwj** [comment]
ronald's comments upon reviewing our standard ONIX output (translation soon to follow):


*    Auteurs. We halen de gegevens bij voorkeur uit DescriptiveDetail/Contributor[ContributorRole='A01']/PersonNameInverted. Jullie hebben de naam alleen aangeleverd als twee aparte elementen (<NamesBeforeKey> en <KeyNames>). Dat heeft niet mijn voorkeur: op het moment dat er meerdere auteurs zijn, en van één van hen ontbreekt de <NamesBeforeKey>, dan bestaat de kans dat de voor- en achternamen op een verkeerde manier worden gekoppeld in ons Excel document. Dus mijn advies: voeg <PersonNameInverted> toe.
 *  BIC en BISAC. Om redenen die ik niet heb kunnen achterhalen werd de BIC code niet opgepikt. Ik heb niet kunnen achterhalen wat er fout ging.
*    Trefwoorden: ik heb de functie in ons Excel document aangepast. Trefwoorden zoals jullie die aanleveren worden nu ook opgepikt.
 *   Jaar van publicatie. Aangezien alle door ONIX gesanctioneerde datum formaten altijd beginnen met YYYY, zullen we alle datums afkorten naar de eerste 4 cijfers
 *   Download link. Ik wil je aanraden om de WebsiteRole aan te passen. In jouw bestand is dit 01 (ProductSupply/SupplyDetail/Supplier/Website[WebsiteRole=01]/WebsiteLink); en volgens de specificaties moet dat 29 zijn.
