### ISSUE TITLE
Output to EBSCO

### ISSUE THREAD

**Issue by ja573** [thoth-pub/thoth#49]

**Comment by vincentwj** [comment]
Recommendation 40. COPIM should meet with EBSCOs discovery team to discuss the potential of supplying OA monograph metadata into the library supply chain

**Comment by rhigman** [comment]
In progress at https://github.com/thoth-pub/thoth/tree/feature/49_ebsco_onix2.1; currently awaiting feedback from EBSCO on an example output file.
