### ISSUE TITLE
Move Copyright assignment from Open Book Publishers to Thoth Open Metadata CIC

### ISSUE THREAD

**Issue by tosteiner** [thoth-pub/thoth#510]
**Is your feature request related to a problem? Please describe.**
At the moment, the copyright on Thoth is still assigned to Open Book Publishers. 

**Describe the solution you'd like**
As noted by @rupertgatti noted in a conversation, it will be good to change that, and assign copyright to Thoth Open Metadata CIC.

**Comment by ja573** [comment]
> @rupertgatti are there any steps that would need to be taken care of from OBP's end, do you think?
> 
> From Thoth's side, I believe we've updated all references over the past months, so could close that issue if nothing else is needed.

We haven't updated the license files in Thoth, they currently read `Copyright 2020 Open Book Publishers`

**Comment by tosteiner** [comment]
oh, thanks, Javi! How about we replace that with 

```
Copyright 
2020-2022 Open Book Publishers
2022-   Thoth Open Metadata

**Comment by ja573** [comment]
Completed in [v0.13.0](https://github.com/thoth-pub/thoth/releases/tag/v0.13.0)
