### ISSUE TITLE
DOI validation doesn't include angle brackets as permitted characters

### ISSUE THREAD

**Issue by rhigman** [thoth-pub/thoth#513]
See #469 - the same issue occurs with the following real-world DOI:

[https://doi.org/10.1002/(SICI)1098-2736(199908)36:6<637::AID-TEA4>3.0.CO;2-9](https://doi.org/10.1002/(SICI)1098-2736(199908)36:6<637::AID-TEA4>3.0.CO;2-9)

In the Thoth UI, pasting this DOI into a DOI field produces an invalid DOI warning, and deleting the angle brackets removes the warning.

**Comment by ja573** [comment]
Getting an error now with `https://doi.org/10.1002/(sici)1096-8644(1996)23+<91::aid-ajpa4>3.0.co;2-c`
