### ISSUE TITLE
Add SciELO to LocationPlatform list

### ISSUE THREAD

**Issue by brendan-oconnell** [thoth-pub/thoth#536]
In order to add SciELO books to Thoth, we need a new LocationPlatform for SciELO. This will be the Location for all Imprints hosted on SciELO, e.g. EDITUS, EDUFBA, EDUEPB. Suggested Value: "SCIELO"

**Comment by ja573** [comment]
Ok, it's already been set to `SCIELO` (serialised as SciELO) in the latest release https://github.com/thoth-pub/thoth/releases/tag/v0.11.14 but haven't deployed it yet, so we can still change it

**Comment by amandasramalho** [comment]
"SCIELO_BOOKS" is fine. The name "SCIELO" alone is usually associated with journals, so it's worth the distinction.
