### ISSUE TITLE
Disseminate to Zenodo

### ISSUE THREAD

**Issue by rhigman** [thoth-pub/thoth#542]
Zenodo have a [rest API](https://developers.zenodo.org/#rest-api) which should facilitate a Thoth Dissemination Service workflow, i.e. submission of files and metadata based on Thoth records (comparable to zenodo/zenodo#361).

Of interest both to WP7 (as an archiving platform) and to Thoth Plus (as a hosting platform option).

**Comment by tosteiner** [comment]
thanks, @rhigman and yup, that was from me 😄 

Commnunity created here: https://zenodo.org/communities/thoth/ - this now allows for users with admin rights to be added, who then can upload to & curate that community.

**Comment by rhigman** [comment]
Ah, perfect, thanks @tosteiner! :smiley:

**Comment by rhigman** [comment]
We may also consider publishing dumps of Thoth data further down the line, and Zenodo would be one option for this. So it would be good if the logic implemented here was reusable for this purpose (granular methods, separate client published to pip [if not using an existing third-party client], etc).

**Comment by tosteiner** [comment]
Re: data dumps, that's a great idea. There are a number of (semi-)automated workflows to facilitate archiving of full GitHub Repos in Zenodo, maybe these can be of use here? See e.g.  https://www.lib.uiowa.edu/data/files/2022/10/Share_and_Preserve_Your_Code_20220728.pdf

**Comment by tosteiner** [comment]
hmm, yeah, you might be right - had assumed this would just take a full repo and upload it to Zenodo, so if we added a data dump to repo X, this would also include that data dump?

**Comment by rhigman** [comment]
Note https://github.com/zenodo/zenodo/issues/2532. Thoth uses the ISO 639-2 "bibliographic" language codes where applicable, rather than the "terminological" ones (both as an underlying representation, and in all relevant outputs). There's a broader question of whether we might need to support the "terminological" versions (where distinct) in any other contexts.
