### ISSUE TITLE
Implement non-OA metadata in export outputs

### ISSUE THREAD

**Issue by tosteiner** [thoth-pub/thoth#544]
**Is your feature request related to a problem? Please describe.**
As a publisher, I want to be able to distribute metadata that pertains to non-OA titles. which isn't fully possible at the moment. 

As a team, we'll need to decide if we want to enable such features.

**Additional context**
- JSTOR ONIX output currently not accurate for non-OA books (White Horse Press use case - fields such as `<Unpriced Item Type>` are output hard-coded); this is probably also the case for some other ONIX outputs
- SciELO publishers: Amanda notes many of them will likely be seeking to use Thoth to manage metadata also for books that are not in SciELO, and non-OA. ONIX fields for e.g. regional dissemination restrictions one particular field that would be needed and is currently missing.
- More generally, other hybrid presses would also benefit from from this expansion.

**Comment by rhigman** [comment]
Similarly to the point about ONIX, the MARC output also currently includes [a blanket OA statement](https://github.com/thoth-pub/thoth/blob/f9cb0f6d8e8627712c02e24a7d6e7eec852331a1/thoth-export-server/src/marc21/marc21record_thoth.rs#L322). This could be amended while fixing #525 (e.g. move under the CC licence check, as per the incorrectly-implemented 1c8a0ce).

**Comment by rhigman** [comment]
To be implemented based on assuming that works with a licence URL supplied are OA, and works without are non-OA.

**Comment by rhigman** [comment]
#629 implements conditional outputting of existing OA-related information, but does not make any changes to the data model, e.g. to add storage of regional dissemination restrictions as mentioned in original description.
