### ISSUE TITLE
Connect with Metadata 2020

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#55]
Recommendation 3. COPIM keeps a watching brief on this project and makes its findings available to Metadata 2020.

**Comment by tosteiner** [comment]
As of Q3 2023, Thoth now is a signatory of the Metadata 2020 pledge https://metadata2020.org/do-more/sign-the-pledge/

To Do:
- [ ] Draft a writeup to compare Thoth's model against the Metadata2020 Best Practices https://metadata2020.org/resources/metadata-practices/ 
- [ ] engage the Metadata2020 core group via email info@metadata2020.org
- [ ] ...
