### ISSUE TITLE
Add L'Harmattan OA to LocationPlatform list

### ISSUE THREAD

**Issue by brendan-oconnell** [thoth-pub/thoth#560]
Create new LocationPlatform in Thoth for L'Harmattan OA books. Suggested value in Thoth: "LHARMATTAN_OA", platform name is "L’Harmattan Open Access"

**Comment by ja573** [comment]
For this use case we should just use `OTHER`, as it's a publisher site. Until https://github.com/thoth-pub/thoth/issues/545#issuecomment-1930344101 is implemented
