### ISSUE TITLE
Overlapping text for Locations in Thoth Admin panel on website in Chromium browsers and Safari

### ISSUE THREAD

**Issue by brendan-oconnell** [thoth-pub/thoth#571]
**Describe the bug**
When a Publication Location has a long URL for Landing Page and Full Text URL, the link text overlaps, making it hard to read. Example: [https://thoth.pub/admin/publication/82d6b392-77cf-4323-8f22-5f53765c9892](https://thoth.pub/admin/publication/82d6b392-77cf-4323-8f22-5f53765c9892)

This is only an issue in Chromium browsers (e.g. Chrome, Brave) and Safari. Links display with wrapped text in Firefox and text doesn't overlap.

<img width="1123" alt="image" src="https://github.com/thoth-pub/thoth/assets/68507084/274822a3-d1db-4a19-a7a8-ded5778aec70">

**Comment by rhigman** [comment]
Oh dear, this is similar to feedback that's been raised before, and there was an attempted fix in b1df853, but I guess the fix didn't cover Chromium/Safari :confused:
