### ISSUE TITLE
Make Thoth records DORA compliant

### ISSUE THREAD

**Issue by tosteiner** [thoth-pub/thoth#615]
One recommendation from our COPIM WP5 Research report has been to make Thoth records compliant with [DORA](https://github.com/thoth-pub/thoth/wiki/DORA) recommendations.

Will need to check DORA recommendations for publishers, figure out technical issues, such as the recording of Reference within metadata record, that might result from those recommendations.

**Comment by rhigman** [comment]
Duplicate of https://github.com/thoth-pub/thoth/issues/534

**Comment by tosteiner** [comment]
oh, apologies - I had forgotten to look through the list of closed issues 🤦🏽‍♂️ Will be closing this now, then 😅
