### ISSUE TITLE
Add audiobook formats to publication types for books and chapters

### ISSUE THREAD

**Issue by rupertgatti** [thoth-pub/thoth#617]
**Is your feature request related to a problem? Please describe.**
Request via OBP to publish audio recordings of book chapters

**Describe the solution you'd like**
Add audiobook formats to publication types for chapters and books
I don't believe there is any need to change the datamodel for digital editions to enable this.

**Additional context**
Most popular audiobook formats are MP3 and WAV.

**Comment by ja573** [comment]
Note to myself: after the new publication types are added to Thoth, we'll need to check if any additional work is needed on the website to implement this (doubt it)
