### ISSUE TITLE
Handling Contributors is painfully slow in the backend, impacting on publishers' workflows

### ISSUE THREAD

**Issue by tosteiner** [thoth-pub/thoth#631]
**Describe the bug**
Am noticing considerable lag when calling up the Contributors dialogue (mainly within the book- and chapter-level lookup of contributors). 

So, for example, when I'm seeking to add a new contributor to a given work, the dialogue freezes for ca. 5 seconds, and my browser (Firefox) issues a warning that "this site is slowing down your system".

Francois from African Minds also noted they're having similar issues, so would be good to find a fix for this to improve contributor data loading

![browser-warning-firefox](https://github.com/user-attachments/assets/8e3e04ce-e0d8-4900-a564-01063e755aaa)

**Comment by ja573** [comment]
We should disable updating the base contributor, and only query the one selected
