### ISSUE TITLE
Adding Canonical Location to a Publication is still buggy 

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#639]
**Describe the bug**
Adding a Canonical Location leads to error message "Each publication should have a canonical location"

**To Reproduce**
1. Go to Edit Publication 
2. Click on Add Location (no previous locations added)
3. Add Landing Page, Full URL, select Publisher Website, Canonical Location Yes

**Expected behavior**
The Location to be added without error, since it's the first and canonical

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1
 - Browser: Firefox
 - Version: 131.0.2

**Additional context**

**Comment by rhigman** [comment]
Thanks for the report. This looks like another instance of the third-party package bug (see e.g. https://github.com/thoth-pub/thoth/issues/366) where the value shown in the dropdown (here "Yes", for Canonical) does not actually reflect the true value of the dropdown (here the default value of "No", hence the error on hitting Save).

To be fixed under #640 by changing the default true value of the Canonical dropdown to "Yes".
