### ISSUE TITLE
ONIX 3.0 adjustments for compliance with Kobo requirements

### ISSUE THREAD

**Issue by amandasramalho** [thoth-pub/thoth#642]
**Is your feature request related to a problem? Please describe.**
The current THOTH ONIX 3.0 has 2 fields that are not accepted for publishing books on Kobo. 

Specifically:
`<ProductAvailability>99</ProductAvailability>`: Kobo does not support code 99. Perhaps code 20 (Available) should be considered as an alternative.
`<UnpricedItemType>04</UnpricedItemType>`: Kobo only accepts code 01 (Free of charge), while code 04 is not supported.

**Describe the solution you'd like**
I propose the following adjustments to the Thoth ONIX 3.0 to meet Kobo's metadata requirements:

Replace `<ProductAvailability>99</ProductAvailability>` with `<ProductAvailability>20</ProductAvailability>` (Available).
Replace `<UnpricedItemType>04</UnpricedItemType>` with `<UnpricedItemType>01</UnpricedItemType>` (Free of charge).

These changes would ensure that the ONIX metadata is compatible with Kobo’s supported codes.

**Describe alternatives you've considered**
There are limited alternatives since Kobo has specific requirements for these fields.
I suggest studying whether these adjustments are relevant for incorporating into Thoth's ONIX or creating a specific ONIX for Kobo.

**Additional context**
Kobo suggests including Thema fields whenever possible and recommends the use of accessibility tags: https://kobocontentoperations.zendesk.com/hc/en-us/articles/22730102538395-Accessibility-FAQs

**Comment by ja573** [comment]
Now live under [v0.12.14](https://github.com/thoth-pub/thoth/releases/tag/v0.12.14)
