### ISSUE TITLE
Output ONIX for Google Books

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#72]
Recommendation 25. In addition to understanding Amazon’s algorithm, COPIM needs to understand more about SEO in Google and Google Books.

**Comment by TomMosterd** [comment]
Contact for Google Books provided by UCL Press:

Google Playbook Publisher Summit: https://events.withgoogle.com/google-play-books-publisher-summit/. Head of Publishing Partnerships, EMEA: Ani Attamian, anin@google.com

**Comment by vincentwj** [comment]
Specifications: https://play.google.com/books/publish/u/1/a/11587728181440237556#list

**Comment by vincentwj** [comment]
From the Google Books team how to deal with zero pricing:

> You can also add the tag <UnpricedItemType /> with a value of "01". 
> 
> As per our official documentation:
> 
> ONIX code specifying products that are free of charge, products where a price has not yet been announced, or products where no price is applicable. In particular, for free of charge products, <UnpricedItemType> 01 should always be used in place of a <Price> composite where the Price amount is zero.
