### ISSUE TITLE
Connect with title management systems

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#81]
Recommendation 34. COPIM should not try to recreate title management systems and this should be out of scope for the project

Recommendation 35. COPIM should liaise with these systems in order to understand how COPIM data for OA monographs could be ingested by these services

**Comment by vincentwj** [comment]
Recommendation 38. COPIM needs to conduct further work to understand whether it wants to offer the full service that BiblioVault offers, or just a metadata service.

**Comment by slimdave** [comment]
Happy to liase with your project on this!

https://www.consonance.app

I think we have some third party organisations in common, in that we send ONIX to BDS, Project Muse, OAPEN ... maybe others. Our client list includes quite a few university presses (UCL, University of London, Liverpool, Sydney, Notre Dame, Leuven etc) with varying degrees of OA involvement.

**Comment by ja573** [comment]
What's the best way to contact you, @slimdave ?
