### ISSUE TITLE
Connect with BIC

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#85]
Recommendation 44. COPIM should investigate the BIC accreditation scheme to demonstrate the quality of their metadata

**Comment by tosteiner** [comment]
Could be useful for Thoth to submit a response to the BIC survey that is part of their **Metadata Capabilities Directory** https://bic.org.uk/resources/metadata-capabilities-directory/

**Comment by tosteiner** [comment]
Regarding their accreditation scheme, BIC has three main awards for which applications can be submitted

* **[Supply Chain Excellence Award](https://bic.org.uk/resources/accreditations-overview/supply-chain-excellence-award/)**: applications invited every quarter; eligible stakeholders include Booksellers, Distributors, Printers, Publishers, Service Providers, Systems Vendors, and Wholesalers.
* **[Technology Excellence in Libraries Award](https://bic.org.uk/resources/accreditations-overview/technology-excellence-in-libraries-award/)**: applications invited every two-to-three months, by libraries and their suppliers. The "scheme encourages and rewards libraries and their suppliers for their adoption of best practice and industry standards and their investment in beneficial technologies."
* **[Metadata Excellence Award](https://bic.org.uk/resources/accreditations-overview/metadata-excellence-award/)**: applications invited by publishers; the "scheme is designed to encourage publishers to appreciate the contribution made by accurate and timely product data to their sales; to enable them to demonstrate their commitment to making that data available in the supply chain; and to enable them to benchmark their performance against their competitors."
