### ISSUE TITLE
Connect with Funder Registry

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#91]
Recommendation 56. COPIM needs to keep a watching brief on Funder Registry and build in the possibility of adding three additional pieces of metadata - funder name, funder id, and grant id.

**Comment by tosteiner** [comment]
For documentation purposes: Open Funder Registry to transition into Research Organization Registry (ROR) - https://www.crossref.org/blog/open-funder-registry-to-transition-into-research-organization-registry-ror/
