### ISSUE TITLE
Connect with ISNI

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#93]
Recommendation 57. COPIM should keep a watching brief on ROR and ISNI and include institutional identifiers when and as needed or adopted

**Comment by tosteiner** [comment]
As of Q3 2023, Thoth now is a signatory of the Metadata 2020 pledge https://metadata2020.org/do-more/sign-the-pledge/

To Do:
- [ ] Draft a writeup to compare Thoth's model against the Metadata2020 Best Practices https://metadata2020.org/resources/metadata-practices/ 
- [ ] engage the Metadata2020 core group via email info@metadata2020.org
- [ ] ...
